Metrics/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 25

Style/StringLiterals:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/*

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false
