Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/*

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false